### ISSUE TITLE
colors: allow ansi terminal color names

### ISSUE THREAD

**Issue by colemickens** [dj95/zjstatus#14]
Hi,

With my nixos and home-manager configuration, I have a `hostColor` set. This is then used for my nushell prompt. It gives me a quick at-a-glance indication of what machine I'm on or connected to.

Right now, this is specified as a ansi terminal color name like "cyan", "blue", etc. see: https://www.nushell.sh/commands/docs/ansi.html

The nice benefit of this is that it matches the specified terminal scheme, rather than being "fixed" to a hex value.

Does it make sense to support that here? I'm not sure if zjstatus is handling the format specifiers, or if that comes from zellij through the plugin API.

**Comment by dj95** [comment]
Hi,

you can already use the terminal colours via ansi codes instead of a hex color (e.g. `2` would be the configured green color in your terminal).

However, it would be more intuitive the way you suggest. In #12 is a request for using the colours configured in Zellij. I'm currently not sure how to implement both in a way that is not too complicated.

What do you think about implementing terminal colours by their name (e.g. `blue`) and zellij palette colours by `$colorname` (e.g. `$blue`)? This way we can differentiate between the variable from zellij and the terminal color.

**Comment by colemickens** [comment]
>What do you think about implementing terminal colours by their name (e.g. blue) and zellij palette colours by $colorname (e.g. $blue)? This way we can differentiate between the variable from zellij and the terminal color.

seems elegant and intuitive enough

**Comment by dj95** [comment]
It's implemented and released in v0.6.0
