### ISSUE TITLE
Flash of text when creating tabs

### ISSUE THREAD

**Issue by oredaze** [dj95/zjstatus#33]
When creating new tabs (often, but not always) there will be a very quick flash of text behind the tabs that says something like:
`Loading probablyfilepath/zjstatus.wasm`

Is it a speed issue? I thought rust is fast. Or is it wasm's fault?

**Comment by oredaze** [comment]
Loading it as file.
I have nvme ssd, Ryzen 5 (3.6 GHz) running on gentoo, so I doubt I am the problem.
Do you not see it when quickly adding and removing tabs?

**Comment by dj95** [comment]
I don't see it on my M1Pro MacBook pro, unfortunately. Even when I switch it really fast. Also loading it via a file.

**Comment by dj95** [comment]
Can you post your layout, please? I'll take a look into it, when I have time an want to try to reproduce this on my Linux desktop. Then I'll test your setup and compare it

**Comment by oredaze** [comment]
I copied your example from the readme just now to try it and there is no difference.

**Comment by bphenriques** [comment]
> Basically zellij is creating a new instance of the plugin for each tab. How do you load zjstatus? By file or via http? How are your hardware specs?

It would be nice if it was a single instance across all tabs. At least for some, including my case where I just have the tab list, the weather and a clock.

**Comment by Jedsek** [comment]
The same problem when adding new tabs(removing has good behavior)

**Comment by Jedsek** [comment]
The offical tab bar will also flash (without explicit text `Loading from xxx/xxx.wasm`)

**Comment by dj95** [comment]
I also think, that I cannot do something to resolve the issue within zjstatus, since the loading text comes from loading the plugin from file (and maybe checking/loading a cache). This is also supported by the official tab bar producing the flashing text.

Since it is not an issue within zjstatus, I would kindly ask the author (@oredaze) to open an issue on zellij's side. Feel free to reference this issue to show, that different people care about this feature and to offer a starting point for new users, that are searching for a similar issue.

**Comment by oredaze** [comment]
I haven't noticed the built in zellij bars doing this, but I will try asking there.
