### ISSUE TITLE
Datetime only supports one theme formatting hint

### ISSUE THREAD

**Issue by mrdgo** [dj95/zjstatus#40]
**Describe the bug**
The field `datetime` in the config appears to only support one theming hint. So if I add a fancy special character with inverted color to match the style, the date doesn't get rendered correctly and instead the `#[bg=#...,fg=#...]` is rendered in the status bar.

**To Reproduce**
1. use multiple `#[]` theme hints to the `datetime` field
2. start zellij with zjstatus and the from 1. resulting config

**Expected behavior**
I would have expected that the date is formatted with my desired colors.

**Screenshots**
![image](https://github.com/dj95/zjstatus/assets/1636639/d81943bc-d62a-4290-a597-e1f960fb9e53)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Zellij version: v0.39.2
- version: 0.12.0

**Layout**

```kdl
datetime "#[fg=#98971a,bg=#161616] #[bg=#98971a,fg=#161616]{format} "
```

it renders as
```
 #[bg=#98971a,fg=#161616] Monday ...
```

**Comment by dj95** [comment]
Hi,

thanks for your bug report. As for now, this is intended behaviour, since you can only provide the date/time format in this widget and nothing else. For your purpose, you could add the starting section (`#[fg=#98971a,bg=#161616]`) right before the date widget in `format_left` or `format_right`. Is this a feasible option?
