### ISSUE TITLE
ansicolor default

### ISSUE THREAD

**Issue by nothendev** [dj95/zjstatus#49]
**Is your feature request related to a problem? Please describe.**
yep. i want background blur with alacritty and it only does that if the bg color is set to 49 (ansicolor default). i can use a separate magic 49 for any backgrounds but it feels meh.

**Describe the solution you'd like**
i want a "default" color alias which maps to AnsiColor::Default so i can use it both as a fg and bg (which map to the respective 39/49 values depending on fg or bg)

**Additional context**
alacritty

**Comment by dj95** [comment]
Hi and thanks for your feature request.

Unfortunately it's not that easy to map the color to `AnsiColor::Default` since this does not exist. There's a function `on_default` which allows to render the text on the default background color. Internally, it just creates an empty style with only the foreground color set. The same goes for the default foreground color.

This implementation allows us to recreate the behaviour by just not setting `fg` and `bg` at all. I've tested it in Alacrity on macOS and it looks like this.

<img width="2505" alt="Screenshot 2024-03-16 at 10 47 18" src="https://github.com/dj95/zjstatus/assets/4348959/36bf34a9-4e04-47a7-9126-4c26eef2ba27">

As you can see it is blurring the background and zjstatus will not overpaint the regions. `foo` on the right side of the bar has the default `fg` color. 

Therefore it would be a little bit unintuitive to implement the `default` color, which internally does nothing, since it defaults when not specified.

Does this work for you? If so, we should definitely add it to the documentation.

**Comment by nothendev** [comment]
Also, i don't understand how layering works, i.e. if I do "#[fg=base,bg=blue] a #[fg=blue] b" would "b" be rendered as blue on blue or blue on default? (pretend base is a valid color)

**Comment by dj95** [comment]
There is no layering. So b will be blue on the default background. Each format is resetting everything to default and just rendering the format that is specified in them. This is the main difference in contrast to tmux.

**Comment by nothendev** [comment]
thanks!
