### ISSUE TITLE
Support showing the output of a command

### ISSUE THREAD

**Issue by cor** [dj95/zjstatus#5]
It would be really convenient if you could show the output of an arbitrary command in this statusbar

**Comment by dj95** [comment]
Hi, thanks for your suggestion. I believe it's not possible at the moment since zellij plugins are executed in a wasm sandbox. They are neither able to access the root fs (just a sandboxed part) nor able to run certain programs.

Maybe the zellij api will provide this feature or permission in the future.

**Comment by cor** [comment]
Makes sense, thank you!

**Comment by dj95** [comment]
Found the relating issue on zellijs side.

https://github.com/zellij-org/zellij/issues/2559

Will implement it as soon as the API arrives with zellij.

**Comment by dj95** [comment]
https://github.com/zellij-org/zellij/pull/2862 implemented the feature. I'll try it, when I have time for it with the development version of zellij.

**Comment by dj95** [comment]
Using the feature with the development version of zellij since a week and it seems to be stable (at least on my side). I'll wait for zellijs new release and merge it then directly.

Feel free to test the feature with a development version of zellij.

**Comment by dj95** [comment]
Closed, since zellij 0.39.0 is released and zjstatus 0.9.0 supports now command widgets.
