### ISSUE TITLE
Refreshing the plugin

### ISSUE THREAD

**Issue by zDonik1** [dj95/zjstatus#71]
**Description**

Is there an easy way to refresh the plugin? I believe that the plugin doesn't reread the configuration for existing sessions, even those that have been closed and resurrected, although that must be an issue with zellij itself. I can't get config updates to the status for existing sessions because of it. I have even tried rebooting the system and reattaching to the session.

**Comment by dj95** [comment]
Hi,

unfortunately this is a bug/behavior that I cannot fix in zjstatus. As long as zellij does not refresh the config (or persists it in dead sessions), I cannot do much about this.

The only thing I can imagine, that you could try, is to configure zjstatus as an alias in the config.kdl and reference it in the layouts. I haven't tested this one and it would not refresh zjstatus while running, but maybe you get at least resurrected session with a more recent config.

Otherwise please address this in the zellij repo. They can offer you help with this.

**Comment by zDonik1** [comment]
Thanks for the suggestion.

**Comment by dj95** [comment]
Since I cannot do something about that, I'll close it as "Won't fix". But you can refer to it, if you create the bug on zellijs side.
